language: node_js

node_js:
  - '10.7.0'

script:
  - npm run test --coverage

services:
  - mongodb

cache:
  yarn: true
  directories:
    - 'node_modules'

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.5.1
  - export PATH="$HOME/.yarn/bin:$PATH"

after_success:
  - npm run codecov

